apiVersion: v1
kind: Pod
metadata:
  name: todo-app-pod
spec:
  containers:
  - name: todo-app-container
    image: purnima83/myrepo  # Replace with your Docker image
    ports:
    - containerPort: 80  # Assuming your application listens on port 80

